### ISSUE TITLE
Is this project complete?

### ISSUE THREAD

**Issue by Anri1967** [toscano/hass-autonomic#1]
Trying to integrate this with my homeassistant but I am unable to install in integrations. From logs, I can see it is missing a manifest.json and config_flow files. Do such files exist?

Thank you

**Comment by toscano** [comment]
I've been working in my home so I'll double check that those files are checked in. I'll try to get it done tomorrow.

**Comment by toscano** [comment]
@Anri1967 I fixed the missing file issue, however that should have given you only a WARNING with the latest version of HA. Please ensure that your `configuration` is correct.

**Comment by Anri1967** [comment]
@toscano Thank you for the quick update. Is this supposed to be a full integration? as in when I got to add new integration, am I supposed to see "Autonomic" in my integration drop down menu? As for now, I am seeing them as separate entities where I can select them as media player. I cannot change the zones or sources from this UI. My understanding is that this should work like TuneBridge App? 

This are what I am seeing currently:
![image](https://user-images.githubusercontent.com/80057621/110212057-8dc28980-7e67-11eb-91bf-f8625bb2851c.png)
![image](https://user-images.githubusercontent.com/80057621/110212067-9b780f00-7e67-11eb-99c1-42c95c81500b.png)

**Comment by toscano** [comment]
@Anri1967 I'm glad that it looks as though you've gotten things working... No, it's not a full integration. It only allows for each Autonomic Zone to be represented as a HA Media Player. You have `volume` `power` and `transport` control when appropriate. Additionally the `text-to-speach` feature is exposed.
