### ISSUE TITLE
Received this in the HA logs

### ISSUE THREAD

**Issue by broadcasting101** [toscano/hass-autonomic#2]
Hello! I'm new to this whole "submitting an issue" thing, so I apologize if my first post was rather abrupt.

I'm experiencing an error in Home Assistant 
"Description request to http://192.168.xxx.xxx:5005/upnp/DevDesc/0.xml failed... will try again in 30 seconds.
3:17:19 PM – (WARNING) autonomic (custom integration) - message first occurred at 2:53:49 PM and shows up 48 times

The previous error I had posted no longer appears. I'm unable to access any of the Autonomic gear via Home Assistant. Any assistance you're able to provide would be much appreciated.  Thank you in advance!

**Comment by toscano** [comment]
Sorry for the late reply... this message suggests that your MMS is at a different IP address than the one that's configured and/or is otherwise not accessible by the HomeAssistant box.

**Comment by broadcasting101** [comment]
No problem at all. Thank you Michael! My post was slightly inaccurate. I can ping the MMS at the IP listed in the HA config, from HA. I can also access the config page for the MMS, from the rest of the network, at that same IP.

**Comment by toscano** [comment]
@broadcasting101 

1. What model MMS are you running?
2. What version firmware does it have?
3. What Amplifier(s) are you using?

Try this: Copy the URL from your log file and open it in a web browser on the same network as the MMS... you should see something like this (taken from my MMS directly):

```xml
<root xmlns="urn:schemas-upnp-org:device-1-0">
  <specVersion>
    <major>1</major>
    <minor>0</minor>
  </specVersion>
  <device>
    <URLBase>http://192.168.1.80</URLBase>
    <deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType>
    <friendlyName>MMS-5e</friendlyName>
    <manufacturer>Autonomic Controls</manufacturer>
    <manufacturerURL>http://www.Autonomic-Controls.com</manufacturerURL>
    <modelDescription>Media Control Server</modelDescription>
    <modelName>Media Control Server</modelName>
    <modelNumber>6.4.20220318.2 Release</modelNumber>
    <modelURL>http://www.Autonomic-Controls.com</modelURL>
    <serialNumber>unknown</serialNumber>
    <UDN>uuid:xxxxxx-xxxx-xxxx-xxxx-xxxxxx</UDN>
    <UPC>Autonomic Controls, Inc.</UPC>
    <serviceList/>
    <presentationURL>/</presentationURL>
    <!--  DESC:MMS-5e  -->
    <!--  STORAGE:251906916352  -->
    <!--  AVAILABLE:238903595008  -->
    <!--  CTRLPORT:5004  -->
    <!--  PRODUCT:DMS50  -->
    <!--  PARTNER:Autonomic Controls, Inc.  -->
    <!--  PNRENUM:Autonomic  -->
    <!--  EXT-TRACK:.aac|.aif|.aifc|.aiff|.au|.flac|.m4a|.mp2|.mp3|.mpa|.rmi|.snd|.wav|.wma  -->
    <!--  EXT-PLYST:.m3u|.wpl|.zpl  -->
    <!--  version:mediasyncsetup.version:6.3.20211116.0  -->
    <!--  SSNG:xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx  -->
    <!--  LID:xxxxxx-xxxx-xxxx-xxxx-xxxxxxxx  -->
  </device>
</root>
```

My guess is that the IP address of the MMS in your configuration file is not correct. 
It should be the same one that you use to connect to your config page. Either that or you don't have the proper hardware / firmware combination.

**Comment by toscano** [comment]
@broadcasting101 

Also, you need to update your copy of this custom component and restart HA. The `async_timeout` issue is resolved as of today.

**Comment by broadcasting101** [comment]
You're a gem! Thank you Michael. I copied over the custom component again, restarted HA, and boom!
I've been banging my head against the wall for a while now, and I thought I had done this already. Your time is valued and very much appreciated.

**Comment by toscano** [comment]
@broadcasting101 Happy to help!
