### ISSUE TITLE
Home Assistant Component Integration no Longer Available

### ISSUE THREAD

**Issue by ab-tools** [toscano/hass-autonomic#3]
Hello Michael,

first thanks for making your Autonomic implementation public! :-)

In your code you are referencing more information on
https://home-assistant.io/components/media_player.autonomic/
but it looks like that this Home Assistant component integration page is no longer available.

Is there any particular reason for this?

Best regards and thanks
Andreas

**Comment by toscano** [comment]
Hi Andreas,

My original plan was to get this included in the HA codebase but alas I haven't the time. I'll remove references to the link since it never existed.

Regards,
Michael

**Comment by ab-tools** [comment]
Hello Michael,

thanks for your quick reply!

That's a pity that you don't have time to finish the integration:
As I see that you're a co-founder of Autonomic yourself, is there an API documentation available for the Autonomic e-Series devices that we could use to further work on the Home Assistant integration?

Best regards and thanks again
Andreas

**Comment by toscano** [comment]
@ab-tools the integration is fully functional as long as you have a e-Series media server configured with at least one e-Series amplifier. Just copy to the `custom_components` folder and configure via `configuration.yaml`

I just haven't the time to get this included into the HA codebase.
