### ISSUE TITLE
MMS integration 

### ISSUE THREAD

**Issue by Anri1967** [toscano/hass-autonomic#7]
Hello,
After this new upgrade I am having this issue:
On Settings/Device and Services MMS coming up but after hitting on config. I am getting un error message.
Should I do any additional settigs on YAML?

Thank you in advance,
Anri
![MMS](https://github.com/toscano/hass-autonomic/assets/80057621/326f4141-8d46-4764-a8fd-49361bbb46bd)

**Comment by toscano** [comment]
@Anri1967 sorry you're having this issue. Can you enable debug logging and post those logs here.

Btw I'm traveling to see the eclipse and will try my best to be timely in responding.

**Comment by Anri1967** [comment]
Sorry, 
Enjoy your trip. 
No rush

Regards,
Anri

**Comment by toscano** [comment]
Thanks I will. Do post the log files and I'll take a look.

**Comment by Anri1967** [comment]
![Capture MMS LOG ERROR](https://github.com/toscano/hass-autonomic/assets/80057621/a45b71c7-ef54-45ad-9ba3-5f53f01ed2ce)
Hello,
I got this from system logs.

Thank you

**Comment by toscano** [comment]
I have an idea on what it could be. 

1. Is your MMS a standalone unit (i.e. no Autonomic eSeries Amplifiers) ?
2. Can you tell me what version of firmware your MMS is running ?

I'll need to get back to my "lab" in order to test my idea out. Perhaps you can answer my questions above and let me know by the middle of this week?

Thanks for you patience.

**Comment by Anri1967** [comment]
Hello,
I have MMS-3e (Current firmware 6.6.20231219.0) and M401e amp (Firmvare 6.20b1)It is not standalone unit

P.S. I hope that you enjoyed your trip and got lots of pictures.

Regards,Anri



    On Sunday, April 7, 2024 at 05:05:56 PM EDT, Michael Toscano ***@***.***> wrote:  
 
 


I have an idea on what it could be.
   
   - Is your MMS a standalone unit (i.e. no Autonomic eSeries Amplifiers) ?
   - Can you tell me what version of firmware your MMS is running ?

I'll need to get back to my "lab" in order to test my idea out. Perhaps you can answer my questions above and let me know by the middle of this week?

Thanks for you patience.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  

|  | Virus-free.www.avast.com |

**Comment by toscano** [comment]
OK, my idea didn't pan out. Thanks for the extra info, but I need some more.

1. Did this integration find your MMS or did you enter the IP address ?
2. Can you open this link (with your MMS's IP address) in a web browser and post the response here?

`http://{MMS_IP_ADDRESS}/upnp/DevDesc/0.xml`

I may have a few more things to request you get for me but let's start there.

**Comment by Anri1967** [comment]
Hi Michael,
Thank you again and please see below.

   
   - Did this integration find your MMS or did you enter the IP address ? - ANSWER - Yes, integration automaticaly finds MMS under discowered integration page.
   - Can you open this link (with your MMS's IP address) in a web browser and post the response here?
              This XML file does not appear to have any style information associated with it. The document tree is shown below.
<root xmlns="urn:schemas-upnp-org:device-1-0"><specVersion><major>1</major><minor>0</minor></specVersion><device><URLBase>http://192.168.1.20</URLBase><deviceType>urn:schemas-upnp-org:device:Basic:1</deviceType><friendlyName>Mirage Media Server</friendlyName><manufacturer>Autonomic Controls</manufacturer><manufacturerURL>http://www.Autonomic-Controls.com</manufacturerURL><modelDescription>Media Control Server</modelDescription><modelName>Media Control Server</modelName><modelNumber>6.6.20231219.0 Release</modelNumber><modelURL>http://www.Autonomic-Controls.com</modelURL><serialNumber>unknown</serialNumber><UDN>uuid:52ad2958-ea5c-428f-9860-060d369a9601</UDN><UPC>Autonomic Controls, Inc.</UPC><serviceList/><presentationURL>/</presentationURL></device></root>
    On Wednesday, April 10, 2024 at 04:03:48 PM EDT, Michael Toscano ***@***.***> wrote:  
 
 


OK, my idea didn't pan out. Thanks for the extra info, but I need some more.
   
   - Did this integration find your MMS or did you enter the IP address ?
   - Can you open this link (with your MMS's IP address) in a web browser and post the response here?

http://{MMS_IP_ADDRESS}/upnp/DevDesc/0.xml

I may have a few more things to request you get for me but let's start there.

**Comment by toscano** [comment]
Hmm, this looks OK to me. Try this one and return the result here.

`http://{MMS_IP_ADDRESS}/MirageCfg/jsonModel?t=SystemSettingsModel&_=1`

**Comment by Anri1967** [comment]
It is bringing to MMS configuration page loginPlease see below.


    On Friday, April 12, 2024 at 11:19:13 AM EDT, Michael Toscano ***@***.***> wrote:  
 
 


Hmm, this looks OK to me. Try this one and return the result here.

http://{MMS_IP_ADDRESS}/MirageCfg/jsonModel?t=SystemSettingsModel&_=1

**Comment by toscano** [comment]
OK, I didn't see your image but I think the easiest workaround is to temporarily remove the password from the MMS configuration while your configuring Home Assistant.

**Comment by Anri1967** [comment]
WORKS!
Thank you very much for your efforts and time.



    On Friday, April 12, 2024 at 12:55:03 PM EDT, Michael Toscano ***@***.***> wrote:  
 
 


OK, I didn't see your image but I think the easiest workaround is to temporarily remove the password from the MMS configuration while your configuring Home Assistant.
